# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qresponse', '0002_auto_20161223_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qresponse',
            name='test',
        ),
        migrations.AddField(
            model_name='qresponse',
            name='test_code',
            field=models.CharField(default='test_code', max_length=255),
        ),
    ]
