# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qresponse', '0003_auto_20161224_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='qresponse',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
