# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qresponse', '0004_qresponse_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='qresponse',
            name='correct_ans_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='qresponse',
            name='wrong_ans_marks',
            field=models.FloatField(default=0.0),
        ),
    ]
