# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 12:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0003_auto_20161222_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('profession', models.CharField(default='profession', max_length=255)),
                ('educational_qualification', models.CharField(default='educational qualification', max_length=255)),
                ('student', models.BooleanField(default=False)),
                ('mentor', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_code', models.CharField(default='test_code', max_length=255)),
                ('number_of_question', models.FloatField(default=0.0)),
                ('time_limit', models.FloatField(default=0.0)),
                ('total_marks', models.FloatField(default=0.0)),
                ('marks_obtained', models.FloatField(default=0.0)),
                ('total_time_taken', models.FloatField(default=0.0)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_category.Subscriber')),
                ('test_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.TestTemplate')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_category.Subscriber'),
        ),
    ]
