# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_category', '0002_auto_20161224_1257'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exam',
            new_name='ExamSubscribed',
        ),
    ]
