# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_category', '0003_auto_20161224_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubscribed',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
