# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_category', '0004_examsubscribed_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
